services:

  # Applications

  pact-user-service:
    depends_on:
      pact-postgres:
        condition: service_healthy
    image: "pactfoundation/pact-broker"
    container_name: "pact-broker"
    ports:
      - 9292:9292
    environment:
      - PACT_BROKER_DATABASE_USERNAME=user
      - PACT_BROKER_DATABASE_PASSWORD=password
      - PACT_BROKER_DATABASE_NAME=pact_broker
      - PACT_BROKER_DATABASE_HOST=pact-postgres
      - PACT_BROKER_DATABASE_PORT=5432
      - PACT_BROKER_LOG_LEVEL=INFO


  pact-postgres:
    image: "postgres:14.12"
    container_name: "pact-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      retries: 5
      timeout: 3s